### ISSUE TITLE
Screen Bug

### ISSUE THREAD

**Issue by ServersLLC** [Zzm317/MyInfinity#1]
I am using tablet (Samsung Galaxy Tab4.7) please fix it!!
![screenshot_2018-02-21-14-00-03](https://user-images.githubusercontent.com/36006892/36476658-92ce3ef0-170f-11e8-8874-f42169179924.png)

**Comment by ghost** [comment]
Fixed https://github.com/Zzm317/MyInfinity/commit/14ca90ebe03e3ea78fa3019dac1c6fde0ce68659
