### ISSUE TITLE
当注册好用户后，页面出现错误

### ISSUE THREAD

**Issue by YGdevi** [Zzm317/MyInfinity#11]
![chrome_2018-04-03_22-26-37](https://user-images.githubusercontent.com/21022713/38255326-2013ae82-378e-11e8-9652-9b6b423a0d2d.png)
就出现z这个错误，用的是7.5.0的whmcs

**Comment by YGdevi** [comment]
而且，当把注册的用户删除后，面板便可以正常显示

**Comment by YGdevi** [comment]
![chrome_2018-04-03_22-41-07](https://user-images.githubusercontent.com/21022713/38256193-4c90d208-3790-11e8-81b5-ce3d9e19af79.png)

这是我打开whmcs调试出现的

**Comment by ghost** [comment]
请不要使用任何官方的最新非正式版本

**Comment by YGdevi** [comment]
是正式版的啊。。刚更新的
