### ISSUE TITLE
公告、帮助中心、资源下载均无法正常显示

### ISSUE THREAD

**Issue by Mr-Chatwin** [Zzm317/MyInfinity#12]
WHMCS 7.1.2下公告、帮助中心、资源下载均无法正常显示，控制台无报错。

**Comment by ghost** [comment]
无whmcs712测试环境
whmcs742无问题
建议清理模版缓存后重试

**Comment by Mr-Chatwin** [comment]
已知7.1.2访问公告信息地址为xxx.xxx/announcements.php 7.4.2访问公告信息地址为xxx.xxx/index.php?rp=/announcements，应该是这个原因导致的吧，请问应该如何解决这个问题。

**Comment by ghost** [comment]
更新742
