### ISSUE TITLE
加入购物车无法跳转到结账页面

### ISSUE THREAD

**Issue by iamdalaba** [Zzm317/MyInfinity#13]
加入购物车无法跳转到结账页面

**Comment by ghost** [comment]
请提供WHMCS版本，用的哪个购物车 我这边742测试正常

**Comment by iamdalaba** [comment]
版本是 7.5.1，购物车模板是“Standard Cart”
我想知道怎么让导航栏换个样式。横着摆放

**Comment by ghost** [comment]
我这边测试没有问题
环境 7.5.1
购物车 Standard Cart
