### ISSUE TITLE
Bug UI

### ISSUE THREAD

**Issue by ServersLLC** [Zzm317/MyInfinity#3]
![yy7ofqxtwr8](https://user-images.githubusercontent.com/36006892/36944514-0217c0e0-1faf-11e8-9b30-f11b2255f9e7.jpg)

**Comment by ghost** [comment]
Not reappearing

**Comment by ServersLLC** [comment]
Make icons appear

**Comment by ghost** [comment]
This problem IS NOT REAPPEARING ON MY PC
