### ISSUE TITLE
Bug UI 2

### ISSUE THREAD

**Issue by ServersLLC** [Zzm317/MyInfinity#4]
![vfjndzn2fqm](https://user-images.githubusercontent.com/36006892/36944517-24e2e6f4-1faf-11e8-9bbc-9e3476658926.jpg)

**Comment by ghost** [comment]
Not a bug

**Comment by ServersLLC** [comment]
is it normal that there is a large strip?

**Comment by ghost** [comment]
It's your bug 
Under the alert bell there is a gravatar
