### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by ServersLLC** [Zzm317/MyInfinity#5]
Please, add button to menu "Select language"

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
Updated https://github.com/Zzm317/MyInfinity/blob/master/MyInfinity/includes/navbar.tpl

**Comment by ServersLLC** [comment]
you added languages, but with android in chrome I can not scroll the list of languages, here only some of the languages ​​are visible
